version: '3.8'

services:
  # Customer Management
  customer-service-mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb_data:/data/db

  customer-service:
    container_name: customer-service-app
    restart: always
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app  new Dockerfile setup
    working_dir: /usr/app
    command: [ "npm", "start" ]
    depends_on:
      customer-service-mongodb:
        condition: service_started
      kafka:
        condition: service_started

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_started

  # Kong API Gateway
  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    volumes:
      - kong-db:/var/lib/postgresql/data

  kong-migration:
    image: kong:latest
    command: kong migrations bootstrap
    environment:
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
    depends_on:
      - kong-database

  kong:
    image: kong:latest
    environment:
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      kong-database:
        condition: service_started

  konga:
    image: pantsel/konga:latest
    environment:
      - NODE_ENV=development
      - DB_ADAPTER=postgres
      - DB_URI=postgresql://kong:kong@kong-database:5432/kong
    ports:
      - "1337:1337"
    depends_on:
      kong-database:
        condition: service_started
      kong:
        condition: service_started

volumes:
  mongodb_data:
  rabbitmq_data:
  kong-db:
