version: '3.8'

services:
  customer-service-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb_data:/data/db
  customer-service:
    image: node:18-slim
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: [ "npm", "start" ]
    depends_on:
      customer-service-mongodb:
        condition: service_started
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
volumes:
  mongodb_data:
  rabbitmq_data:
