openapi: 3.0.0
info:
  title: Customer Service API
  version: 1.0.0
paths:
  /customers/login:
    post:
      summary: Customer Login
      description: Allows a customer to log in using their email and password.
      tags: ['customer']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "john.doe@mail.com"
                password:
                  type: string
                  example: "a-very-secure-password-123-#*"
              required:
                - email
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Authentication token
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvbiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
          content:
           application/json:
            schema:
              type: object
              properties:
               message:
                type: string
                description: "Error Message"
                example: "E-mail already in use"
  /customers:
    post:
      summary: Create Customer
      description: Register a new customer with their personal details.
      tags: ['customer']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  example: "John"
                lastName:
                  type: string
                  example: 'Doe'
                email:
                  type: string
                  format: email
                  example: 'john.doe@mail.com'
                cellphone:
                  type: string
                  example: '11999999999'
                password:
                  type: string
                  example: "a-very-secure-password-123-#*"
              required:
                - firstName
                - lastName
                - email
                - cellphone
                - password
      responses:
        '201':
          description: Customer created successfully
        '400':
          description: Bad Request
